name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  main:
    name: All checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run all checks
        run: pnpm run all

      - name: Verify no changes
        run: git diff --exit-code
